### PR TITLE
Added German translation

### PR DESCRIPTION
**Pull request by CodingEmil**
Hey Plant-it community!
<br/>

## Screenshots

<br/>
<br/>
Cheers and happy planting! 🌿🌼

### CODE REVIEW

**Comment by CodingEmil** [comment]
This is my first pull request ever, so I am not quit sure what to do about the conflict :/

**Comment by MDeLuise** [comment]
I apologize for any confusion. I was running some tests on the repository when this PR was created. Could you please resubmit the PR, including only the `app_de.arb` file? You can do this by running:
```
git add frontend/lib/l10n/app_de.arb b/frontend/lib/l10n/app_de.arb
```
Thank you!

**Comment by CodingEmil** [comment]
I am not sure how I am able to do so... Do I have to create a fork for that?
 Could you give me a simple explaination fo that? 
Sorry, I am quite new to this :)

**Comment by MDeLuise** [comment]
No problem at all!
Yes, you have to do all the steps you did before, they were all correct but unfortunately the repository was not in a clean state when you created this pull request.
So you have to:
1. create a fork of this repository
2. create the file `frontend/lib/l10n/app_de.arb`
3. and then create the pull request

**Pull request closed without merging**
